### ISSUE TITLE
[ Fix ] Prueba corta de desempeño físico - Visualización del campo “Tiempo registrado (segundos)”

### ISSUE THREAD

**Issue by MaksMaks98** [Historia-Clinica-La-Rioja/historia_clinica_LR#161]
## Version
2.21.8
## Descripción
Se ha detectado un error al mostrar el campo "tiempo registrado (segundos)". Este error provoca que el tiempo mostrado sea un segundo menos que el originalmente registrado. No se observa un patrón específico, ya que la reducción del segundo ocurre de manera aparentemente aleatoria entre todos los registros de tiempo.
## Pasos para reproducir
1. Ingresamos a hsi-test.larioja.gob.ar
2. Nos logueamos con usuario y contraseña.
3. Seleccionamos “Hospital de Prueba”.
4. Seleccionamos “Historia Clínica”.
5. Ingresamos el DNI del paciente.
6. Seleccionamos el paciente.	
7. Nos dirigimos a la pestaña “Adulto Mayor”.
8. Visualizamos la sección “Prueba de desempeño fisico” en el historial de “Evaluaciones geriatricas”.
9. Visualizamos el PDF haciendo click en el icono de visualización .
10. Visualizamos el documento en las secciones indicadas.
## Resultado actual
**A continuación, se muestran las visualizaciones de 3 pruebas iguales:
Prueba 1**
![image](https://github.com/Historia-Clinica-La-Rioja/historia_clinica_LR/assets/141648316/57a6af35-59b1-465d-a17a-341f4a5ee663)

**Prueba 2**
![image](https://github.com/Historia-Clinica-La-Rioja/historia_clinica_LR/assets/141648316/a9c666a3-fdb2-4741-a1e5-45bac8338dac)

**Prueba 3**
![image](https://github.com/Historia-Clinica-La-Rioja/historia_clinica_LR/assets/141648316/dfec0d12-6fd8-4471-89c5-feeba95b6bab)

## Resultado esperado
Se adjunta un PDF con las respuestas utilizadas. Estas respuestas son las que se espera que se muestren durante las pruebas.
[prueba 1.pdf](https://github.com/user-attachments/files/15973478/prueba.1.pdf)
[prueba 2.pdf](https://github.com/user-attachments/files/15973477/prueba.2.pdf)
[prueba 3.pdf](https://github.com/user-attachments/files/15973476/prueba.3.pdf)
## Información adicional
• Ingresamos con:
Usuario: humberto@gmail.com
Contraseña: Dgsdygsi22
• Datos del paciente:
Nombre: Secundino Angel Guerra
Dni: 7278333

**Comment by RLRama** [comment]
Acá está el que resuelve @RodrigoCba96
