### ISSUE TITLE
FIX. Habilitar FF Parte Anestesico

### ISSUE THREAD

**Issue by Barbara-Alvarez** [Historia-Clinica-La-Rioja/historia_clinica_LR#195]
## ℹ Versión
2.24.5
## ⚠ Descripción 
Se Durante las pruebas realizadas para verificar la disponibilidad de la funcionalidad "Guardar Parte Anestésico como Borrador", se detectó que dicha funcionalidad no se encuentra disponible. Además, se identificó que la funcionalidad "Parte Anestésico" tampoco está habilitada.
Este problema parece estar relacionado con la no activación de la feature flag correspondiente, denominada HABILITAR_PARTE_ANESTESICO_EN_DESARROLLO. Para más información, se puede revisar la documentación de la versión 2.19 de HSI ya que esta funcionalidad corresponde a dicha versión.
## 💡 Pasos para reproducir
1.	Ingresamos a hsi-dev.nubecenter.com.ar
2.	Nos logueamos con usuario y contraseña.
3.	Seleccionamos “Hospital Escuela y de Clinicas “VIRGEN MARIA DE FÁTIMA””.
4.	Seleccionamos “Historia Clínica”.
5.	Ingresamos el DNI del paciente.
6.	Seleccionamos el paciente.	
7.	Cliqueamos en el botón “+ACCIONES”
8.	Visualizamos la sección “INTERNACION”
9.	Corroboramos que no se encuentra presente la opción “Parte anestésico”.
## ❌ Resultado actual

 
![image](https://github.com/user-attachments/assets/325a9c60-806a-49d3-95b9-5492a65a3e1e)

	

## ✅ Resultado esperado
 
![image](https://github.com/user-attachments/assets/8f22bb99-1a74-4d80-8b5b-96a7e687216c)

## ℹ Información adicional
•	Ingresamos con:
		Usuario: avrodriguez
		Contraseña: Av29424678
•	Datos del paciente:
Nombre: Maria Lourdes FARALDO PORRA
Dni: 40939406

**Comment by cquevedox** [comment]
Se habilitó la Feature Flag solicitada en los servidores de desarrollo y testing
