### ISSUE TITLE
Fix. Habilitar FF Áreas Sanitarias

### ISSUE THREAD

**Issue by Barbara-Alvarez** [Historia-Clinica-La-Rioja/historia_clinica_LR#196]
## ℹ Versión
2.24.5
 ## ⚠ Descripción 
Se ha detectado que la feature flag HABILITAR_AREA_RESPONSABILIDAD_SANITARIA se encuentra deshabilitada. Esta configuración es necesaria para poder realizar el testing de la nueva funcionalidad “Areas Sanitarias”.
## 💡 Pasos para reproducir
1.	Ingresamos a hsi-dev.nubecenter.com.ar
2.	Nos logueamos con usuario y contraseña.
3.	Visualizamos el módulo “Áreas Sanitarias” en el menú izquierdo.
## ❌ Resultado actual

 
	
![image](https://github.com/user-attachments/assets/f80a10ea-2c24-4f53-864d-8b0952012fcc)

## ✅ Resultado esperado
 
(no se cuenta con imagen del resultado ya que en el entorno de nacion no tenemos roles de prueba con el rol requerido)

## ℹ Información adicional
•	Ingresamos con:
		Usuario: avrodriguez
		Contraseña: Av29424678

**Comment by cquevedox** [comment]
Se activó la feature flag solicitada en los servidores de desarrollo y testing
