### ISSUE TITLE
Fix. [Reporte enfermería- ambulatorio] Valores de la columna evolución.

### ISSUE THREAD

**Issue by Barbara-Alvarez** [Historia-Clinica-La-Rioja/historia_clinica_LR#215]
## ℹ Versión
2.30.2
## ⚠ Descripción 
	Se ha detectado que la columna "Evolución" no muestra los datos previamente cargados en la consulta correspondiente, lo que afecta al reporte de "Enfermería - Ambulatorio". Para la realización de las pruebas, se completaron consultas de enfermería con el fin de verificar la correcta visualización de los datos en el reporte, identificando esta incidencia. Los datos de una consulta realizada son: 
•	Prestador: María Eugenia Carrizo
•	Paciente: José Contreras
•	DNI: 26355900
•	Fecha de atención: 15-10-2024
•	Hora: 12:12
•	Evolucion: “esto es una prueba, por favor tener en cuenta este campo”

## 💡 Pasos para reproducir
1.	Ingresamos a hsi-test.larioja.gob.ar
2.	Nos logueamos con usuario y contraseña.
3.	Seleccionamos “CAPS 20 de Mayo”.
4.	Seleccionamos “Reportes provinciales”.
5.	Seleccionamos la pestaña “Enfermeria”.
6.	Seleccionamos el tipo de reporte como “Ambulatorio”.	
7.	El periodo del informe será: 01/10/2024 a 31/10/2024.
8.	Comprobamos que la ultima columna, que corresponde con “Evolucion”, no muestra los valores cargados en la consulta.
## ❌ Resultado actual

	 
![image](https://github.com/user-attachments/assets/0f42defe-e7a6-476a-85c9-4c88d8111cf2)

## ✅ Resultado esperado
 
![image](https://github.com/user-attachments/assets/db0e3aa0-91ea-40f6-9f61-6f00b58e790e)

## ℹ Información adicional
•	Ingresamos con:
		Usuario: eugeniacarrizi@gmail.com
		Contraseña: Dgsdygsi24
Adjunto PDF de la consulta de prueba:
[bb057df7-e96f-4c08-a306-caa83652fe6d.pdf](https://github.com/user-attachments/files/17397282/bb057df7-e96f-4c08-a306-caa83652fe6d.pdf)

**Comment by RLRama** [comment]
Adjuntado [acá](https://tree.taiga.io/project/rlrama-tablero-de-scrum-ministerio-de-salud-publica-de-la-rioja/us/192) el .xls con este fix listo
