### ISSUE TITLE
Bug de visualización en Pop-Ups

### ISSUE THREAD

**Issue by Barbara-Alvarez** [Historia-Clinica-La-Rioja/historia_clinica_LR#43]
# Version
2.8.10
# Descripcion
Durante la ejecución de la prueba de integración para evaluar si la implementación de la pestaña "Adulto Mayor" afecta el correcto funcionamiento de las demás funcionalidades en el sistema, se identificó un problema al seguir los pasos que se detallan en la siguiente sección.
Al realizar únicamente el último paso, se observó que cualquier pop-up que aparezca en la pantalla carece de la propiedad "padding". Este problema se evidencia al realizar pruebas en la sección "Nueva Consulta" al buscar un problema, ya que el buscador de problemas, que es un pop-up, presenta la misma carencia de "padding". Además, al agregar una "Nueva Orden Ambulatoria" en la pestaña "Estudio", el pop-up resultante también exhibe este error.

# Paso a paso
1.	Ingresamos a hsi-test.larioja.gob.ar
2.	Nos logueamos con usuario y contraseña.
3.	Seleccionamos “Hospital de Prueba”.
4.	Seleccionamos “Historia Clínica”.
5.	Ingresamos el DNI del paciente.
6.	Seleccionamos el paciente.	
7.	Nos dirigimos a la pestaña “Adulto mayor”.
8.	Cliqueamos el botón “Agregar Estudio”
# Tareas 
Se recomienda investigar y corregir este inconveniente para garantizar la consistencia y el funcionamiento adecuado de la interfaz de usuario en todas las secciones mencionadas.
# Resultado actual
![image](https://github.com/Historia-Clinica-La-Rioja/historia_clinica_LR/assets/94334821/75a75b11-c0df-40cb-849b-3ca962a33ae5)
# Resultado esperado
![image](https://github.com/Historia-Clinica-La-Rioja/historia_clinica_LR/assets/94334821/940f9416-408b-46c3-87dd-ac53719e8150)
# Informacion adicional 

- Ingresamos con:
		Usuario: humberto@gmail.com
		Contraseña: Dgsdygsi22

- Datos del paciente:
Nombre: Secundino Angel Guerra
Dni: 7278333

# Recursos adicionales
https://trello.com/c/8nQ9TZab/153-fix-bug-de-visualizaci%C3%B3n-en-pop-ups

**Comment by cquevedox** [comment]
this issue was closed in PR #34
